# Generated by Django 4.2.11 on 2024-05-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelregistration', '0002_locationentry'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='locationentry',
            constraint=models.UniqueConstraint(fields=('location', 'user'), name='location_and_user_uniq'),
        ),
    ]
