# Generated by Django 4.2.12 on 2024-05-12 08:45

from django.db import migrations


def add_prefectures(apps, schema_editor):
    Region = apps.get_model('travelregistration', 'Region')
    Location = apps.get_model('travelregistration', 'Location')

    Region.objects.all().delete()
    Location.objects.all().delete()

    region_kantou = Region(name="関東", color="#094")
    region_touhoku = Region(name="東北", color="#488")
    region_hokuriku = Region(name="北陸", color="#880")
    region_chuubu = Region(name="中部", color="#844")
    region_kinnki = Region(name="近畿", color="#848")
    region_sikkoku = Region(name="四国", color="#440")
    region_kyushu = Region(name="九州", color="#840")
    region_chugoku = Region(name="中国", color="#080")
    region_okinawa = Region(name="沖縄", color="#88f")
    region_hokaido = Region(name="北海道", color="#448")
    Region.objects.bulk_create([
        region_kantou, region_touhoku, region_hokuriku, region_chuubu, region_kinnki, region_sikkoku, region_kyushu,
        region_chugoku, region_okinawa, region_hokaido,
    ])

    Location.objects.bulk_create([
        Location(name_en="hokkaido", name="北海道", region=region_hokaido,
                 display_x=13, display_y=1, display_width=2, display_height=3),

        Location(name_en="aomori", name="青森", region=region_touhoku,
                 display_x=13, display_y=5, display_width=2, display_height=1),
        Location(name_en="iwate", name="岩手", region=region_touhoku,
                 display_x=14, display_y=6, display_width=1, display_height=1),
        Location(name_en="miyagi", name="宮城", region=region_touhoku,
                 display_x=14, display_y=7, display_width=1, display_height=1),
        Location(name_en="akita", name="秋田", region=region_touhoku,
                 display_x=13, display_y=6, display_width=1, display_height=1),
        Location(name_en="yamagata", name="山形", region=region_touhoku,
                 display_x=13, display_y=7, display_width=1, display_height=1),
        Location(name_en="fukushima", name="福島", region=region_touhoku,
                 display_x=13, display_y=8, display_width=2, display_height=1),

        Location(name_en="ibaraki", name="茨城", region=region_kantou,
                 display_x=14, display_y=10, display_width=1, display_height=1),
        Location(name_en="tochigi", name="栃木", region=region_kantou,
                 display_x=14, display_y=9, display_width=1, display_height=1),
        Location(name_en="gunma", name="群馬", region=region_kantou,
                 display_x=13, display_y=9, display_width=1, display_height=1),
        Location(name_en="saitama", name="埼玉", region=region_kantou,
                 display_x=13, display_y=10, display_width=1, display_height=1),
        Location(name_en="chiba", name="千葉", region=region_kantou,
                 display_x=14, display_y=11, display_width=1, display_height=1),
        Location(name_en="tokyo", name="東京", region=region_kantou,
                 display_x=13, display_y=11, display_width=1, display_height=1),
        Location(name_en="kanagawa", name="神奈川", region=region_kantou,
                 display_x=13, display_y=12, display_width=1, display_height=1),
        Location(name_en="yamanashi", name="山梨", region=region_kantou,
                 display_x=12, display_y=11, display_width=1, display_height=1),
        Location(name_en="nagano", name="長野", region=region_kantou,
                 display_x=12, display_y=9, display_width=1, display_height=2),

        Location(name_en="niigata", name="新潟", region=region_hokuriku,
                 display_x=12, display_y=8, display_width=1, display_height=1),
        Location(name_en="toyama", name="富山", region=region_hokuriku,
                 display_x=11, display_y=8, display_width=1, display_height=1),
        Location(name_en="ishikawa", name="石川", region=region_hokuriku,
                 display_x=10, display_y=8, display_width=1, display_height=1),
        Location(name_en="fukui", name="福井", region=region_hokuriku,
                 display_x=10, display_y=9, display_width=1, display_height=1),

        Location(name_en="gifu", name="岐阜", region=region_chuubu,
                 display_x=11, display_y=9, display_width=1, display_height=2),
        Location(name_en="shizuoka", name="静岡", region=region_chuubu,
                 display_x=12, display_y=12, display_width=1, display_height=1),
        Location(name_en="aichi", name="愛知", region=region_chuubu,
                 display_x=11, display_y=11, display_width=1, display_height=1),
        Location(name_en="mie", name="三重", region=region_chuubu,
                 display_x=10, display_y=11, display_width=1, display_height=1),

        Location(name_en="shiga", name="滋賀", region=region_kinnki,
                 display_x=10, display_y=10, display_width=1, display_height=1),
        Location(name_en="kyoto", name="京都", region=region_kinnki,
                 display_x=9, display_y=10, display_width=1, display_height=1),
        Location(name_en="osaka", name="大阪", region=region_kinnki,
                 display_x=8, display_y=11, display_width=1, display_height=1),
        Location(name_en="hyogo", name="兵庫", region=region_kinnki,
                 display_x=8, display_y=10, display_width=1, display_height=1),
        Location(name_en="nara", name="奈良", region=region_kinnki,
                 display_x=9, display_y=11, display_width=1, display_height=1),
        Location(name_en="wakayama", name="和歌山", region=region_kinnki,
                 display_x=8, display_y=12, display_width=2, display_height=1),

        Location(name_en="tottori", name="鳥取", region=region_chugoku,
                 display_x=7, display_y=10, display_width=1, display_height=1),
        Location(name_en="shimane", name="島根", region=region_chugoku,
                 display_x=6, display_y=10, display_width=1, display_height=1),
        Location(name_en="okayama", name="岡山", region=region_chugoku,
                 display_x=7, display_y=11, display_width=1, display_height=1),
        Location(name_en="hiroshima", name="広島", region=region_chugoku,
                 display_x=6, display_y=11, display_width=1, display_height=1),
        Location(name_en="yamaguchi", name="山口", region=region_chugoku,
                 display_x=5, display_y=10, display_width=1, display_height=2),

        Location(name_en="tokushima", name="徳島", region=region_sikkoku,
                 display_x=7, display_y=14, display_width=1, display_height=1),
        Location(name_en="kagawa", name="香川", region=region_sikkoku,
                 display_x=7, display_y=13, display_width=1, display_height=1),
        Location(name_en="ehime", name="愛媛", region=region_sikkoku,
                 display_x=6, display_y=13, display_width=1, display_height=1),
        Location(name_en="kochi", name="高知", region=region_sikkoku,
                 display_x=6, display_y=14, display_width=1, display_height=1),

        Location(name_en="fukuoka", name="福岡", region=region_kyushu,
                 display_x=2, display_y=10, display_width=1, display_height=1),
        Location(name_en="saga", name="佐賀", region=region_kyushu,
                 display_x=1, display_y=10, display_width=1, display_height=1),
        Location(name_en="nagasaki", name="長崎", region=region_kyushu,
                 display_x=1, display_y=11, display_width=1, display_height=1),
        Location(name_en="kumamoto", name="熊本", region=region_kyushu,
                 display_x=2, display_y=11, display_width=1, display_height=1),
        Location(name_en="oita", name="大分", region=region_kyushu,
                 display_x=3, display_y=10, display_width=1, display_height=1),
        Location(name_en="miyazaki", name="宮崎", region=region_kyushu,
                 display_x=3, display_y=11, display_width=1, display_height=2),
        Location(name_en="kagoshima", name="鹿児島", region=region_kyushu,
                 display_x=1, display_y=12, display_width=2, display_height=1),

        Location(name_en="okinawa", name="沖縄", region=region_okinawa,
                 display_x=1, display_y=14, display_width=1, display_height=1),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('travelregistration', '0004_location_name_en_alter_locationentry_status'),
    ]

    operations = [
        migrations.RunPython(add_prefectures)
    ]
