# Generated by Django 4.2.12 on 2024-05-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelregistration', '0005_add_prefectures'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='border_radius_bottom_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='border_radius_bottom_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='border_radius_top_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='border_radius_top_right',
            field=models.BooleanField(default=False),
        ),
    ]
