# Generated by Django 4.2.12 on 2024-05-12 08:45

from django.db import migrations


def add_prefectures_radius(apps, schema_editor):
    Location = apps.get_model('travelregistration', 'Location')
    Location.objects.filter(name__in=(
        "北海道",
        "青森",
        "石川",
        "山口",
        "佐賀",
        "愛媛",
        "沖縄",
    )).update(border_radius_top_left=True)
    Location.objects.filter(name__in=(
        "北海道",
        "山口",
        "鹿児島",
        "高知",
        "静岡",
        "和歌山",
        "沖縄",
    )).update(border_radius_bottom_left=True)
    Location.objects.filter(name__in=(
        "北海道",
        "青森",
        "大分",
        "香川",
        "沖縄",
    )).update(border_radius_top_right=True)
    Location.objects.filter(name__in=(
        "北海道",
        "千葉",
        "神奈川",
        "和歌山",
        "徳島",
        "宮崎",
        "沖縄",
    )).update(border_radius_bottom_right=True)


class Migration(migrations.Migration):
    dependencies = [
        ('travelregistration', '0006_location_border_radius_bottom_left_and_more'),
    ]

    operations = [
        migrations.RunPython(add_prefectures_radius)
    ]
