# Generated by Django 4.2.12 on 2024-05-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelregistration', '0007_add_prefectures_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationentry',
            name='status',
            field=models.CharField(choices=[('lived', 'Lived'), ('stayed', 'Stayed'), ('walked', 'Walked'), ('passed through', 'Passed Through'), ('none', 'None')], max_length=64),
        ),
    ]
