# Generated by Django 5.2.14 on 2026-05-16 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelregistration', '0008_alter_locationentry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='locationentry',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('lived', 'Lived'), ('stayed', 'Stayed'), ('walked', 'Walked'), ('passed through', 'Passed Through')], max_length=64),
        ),
        migrations.AddField(
            model_name='region',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelregistration.map'),
        ),
    ]
