# Generated by Django 5.2.14 on 2026-05-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelregistration', '0013_make_location_region_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='map',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
